/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import javax.swing.ImageIcon;

/**
 *
 * @author BEPIS
 */
public class eje3 extends javax.swing.JFrame {
double tv,lapto,equipo,disco,costo;
    public eje3() {
        initComponents();
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btncalcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txtsubtotal = new javax.swing.JTextField();
        chbxtv = new javax.swing.JCheckBox();
        chbxdisco = new javax.swing.JCheckBox();
        chbxequipo = new javax.swing.JCheckBox();
        chbxlapto = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txtigv = new javax.swing.JTextField();
        btnlimpiar = new javax.swing.JButton();
        jLabelequipo = new javax.swing.JLabel();
        jLabellapto = new javax.swing.JLabel();
        jLabeltv = new javax.swing.JLabel();
        jLabeldisco = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtregistro = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ventas de Equipos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        btncalcular.setText("CALCULAR");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel2.setText("DNI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("Direccion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 160, -1));
        getContentPane().add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 210, -1));
        getContentPane().add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 90, -1));

        chbxtv.setText("tv LED 52");
        chbxtv.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbxtvStateChanged(evt);
            }
        });
        getContentPane().add(chbxtv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        chbxdisco.setText("disco duro externo 1T");
        chbxdisco.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbxdiscoStateChanged(evt);
            }
        });
        getContentPane().add(chbxdisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        chbxequipo.setText("equipo de sonido 10W");
        chbxequipo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbxequipoStateChanged(evt);
            }
        });
        getContentPane().add(chbxequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        chbxlapto.setText("lapto TOSHIBA I9");
        chbxlapto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbxlaptoStateChanged(evt);
            }
        });
        getContentPane().add(chbxlapto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel5.setText("IGV");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        jLabel6.setText("Total");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        jLabel7.setText("Sub total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 90, -1));
        getContentPane().add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, -1));
        getContentPane().add(txtigv, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 90, -1));

        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 80, -1));
        getContentPane().add(jLabelequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 180, 140));
        getContentPane().add(jLabellapto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, 140));
        getContentPane().add(jLabeltv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 180, 140));
        getContentPane().add(jLabeldisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 180, 140));

        txtregistro.setColumns(20);
        txtregistro.setRows(5);
        jScrollPane1.setViewportView(txtregistro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 386, 720, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
      
     String registro;
     
      costo=0;
      
      if(chbxlapto.isSelected()){
      costo=costo + lapto;
      }
      if(chbxtv.isSelected()){
      costo=costo + tv;
      }
      if(chbxdisco.isSelected()){
      costo=costo + disco;
      }
      if(chbxequipo.isSelected()){
      costo=costo + equipo;
      }
      double igv=costo*0.18;
      txtsubtotal.setText(String.valueOf(costo));
      txtigv.setText(String.valueOf(igv));
      txttotal.setText(String.valueOf(costo+igv));
      registro=txtregistro.getText()+ " dni " +txtdni.getText()+ " nombre " +txtnombre.getText()+" direccion "+txtdireccion.getText()+ "subtotal " +txtsubtotal.getText()+ " igv " +txtigv.getText()+ " total " + txttotal.getText();
     
      txtregistro.setText(registro+"\n");
    }//GEN-LAST:event_btncalcularActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      lapto=3500;
      tv=1500;
      disco=2000;
      equipo=5000;
    }//GEN-LAST:event_formWindowOpened

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
      txtdni.setText("");
      txtnombre.setText("");
      txtdireccion.setText("");
      txtsubtotal.setText("");
      txtigv.setText("");
      txttotal.setText("");
      txtregistro.setText("");
      
      chbxlapto.setSelected(false);
      chbxtv.setSelected(false);
      chbxdisco.setSelected(false);
      chbxequipo.setSelected(false);
      
     
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void chbxlaptoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbxlaptoStateChanged
       
        if(chbxlapto.isSelected()){
        this.jLabellapto.setIcon(new ImageIcon("..\\laboratorio11_chura\\build\\classes\\formularios\\imagenes\\laptotoshiba.jpg"));
       }
        else{
            this.jLabellapto.setIcon(null);
        }
        
    }//GEN-LAST:event_chbxlaptoStateChanged

    private void chbxtvStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbxtvStateChanged
        if(chbxtv.isSelected()){
         this.jLabeltv.setIcon(new ImageIcon("..\\laboratorio11_chura\\build\\classes\\formularios\\imagenes\\tv.jpg"));
        }else{
        this.jLabeltv.setIcon(null);
        }
    }//GEN-LAST:event_chbxtvStateChanged

    private void chbxdiscoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbxdiscoStateChanged
       if(chbxdisco.isSelected()){
        this.jLabeldisco.setIcon(new ImageIcon("..\\laboratorio11_chura\\build\\classes\\formularios\\imagenes\\disco.jpg"));
        }else{
       this.jLabeldisco.setIcon(null);
       }
    }//GEN-LAST:event_chbxdiscoStateChanged

    private void chbxequipoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbxequipoStateChanged
        if(chbxequipo.isSelected()){
        this.jLabelequipo.setIcon(new ImageIcon("..\\laboratorio11_chura\\build\\classes\\formularios\\imagenes\\equiposonido.jpg"));
        }else{
        this.jLabelequipo.setIcon(null);
        }
    }//GEN-LAST:event_chbxequipoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eje3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eje3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eje3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eje3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eje3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JCheckBox chbxdisco;
    private javax.swing.JCheckBox chbxequipo;
    private javax.swing.JCheckBox chbxlapto;
    private javax.swing.JCheckBox chbxtv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabeldisco;
    private javax.swing.JLabel jLabelequipo;
    private javax.swing.JLabel jLabellapto;
    private javax.swing.JLabel jLabeltv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtigv;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextArea txtregistro;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
