/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

import java.util.ArrayList;

/**
 *
 * @author BEPIS
 */
public class eje4 extends javax.swing.JFrame {

    /**
     * Creates new form eje4
     */
    public eje4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        btnvisualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultadoDerecha = new javax.swing.JTextArea();
        btnanterior = new javax.swing.JButton();
        btnsiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultadoCentrado = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultadoIzquierda = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Asterisco");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel2.setText("Ingrese un numero");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        getContentPane().add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 110, -1));

        btnvisualizar.setText("visualizar");
        btnvisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvisualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnvisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 80, -1));

        txtResultadoDerecha.setColumns(20);
        txtResultadoDerecha.setRows(5);
        jScrollPane2.setViewportView(txtResultadoDerecha);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 160, 140));

        btnanterior.setText("Anterior");
        btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 80, -1));

        btnsiguiente.setText("Siguiente");
        btnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnsiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 80, -1));

        txtResultadoCentrado.setColumns(20);
        txtResultadoCentrado.setRows(5);
        jScrollPane1.setViewportView(txtResultadoCentrado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 160, 140));

        txtResultadoIzquierda.setColumns(20);
        txtResultadoIzquierda.setRows(5);
        jScrollPane3.setViewportView(txtResultadoIzquierda);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvisualizarActionPerformed
       generarResultadoIzquierda(); 
       generarResultadoCentral();
       generarResultadoDerecha();
    }//GEN-LAST:event_btnvisualizarActionPerformed
    
    private void generarResultadoIzquierda(){
        int numero = Integer.parseInt(txtnumero.getText());
        String saltoLinea = "\n";
        String lineas = "";
        for(int i=1;i<=numero;i++){
            String asteriscos = generarAsteriscos(i);
            lineas += asteriscos+saltoLinea;
        }
        txtResultadoIzquierda.setText(lineas);
    }
    
    private void generarResultadoCentral(){
        int numero = Integer.parseInt(txtnumero.getText());
        String saltoLinea = "\n";
        String lineas = "";
        int cantidadAsteriscos = 1;
        int cantidadEspacios = numero-1;
        for(int i=1;i<=numero;i++){
            String espacios = generarEspacios(cantidadEspacios);
            String asteriscos = generarAsteriscos(cantidadAsteriscos);
            cantidadEspacios -= 1;
            cantidadAsteriscos += 2;   
            lineas += espacios+asteriscos+saltoLinea;
        }
        txtResultadoCentrado.setText(lineas);
    }
    
    private String generarAsteriscos(int cantidadAsteriscos){
        String asteriscos = "";
        for(int k=1;k<=cantidadAsteriscos;k++){
                asteriscos += "*";
            } 
        return asteriscos;
    }
    
    private String generarEspacios(int cantidadEspacios){
        String espacios = "";
        for(int j=1;j<=cantidadEspacios;j++){
                espacios += " ";
            }
        return espacios;
    }
    
    private void generarResultadoDerecha(){
        int numero = Integer.parseInt(txtnumero.getText());
        String saltoLinea = "\n";
        String lineas = "";
        int cantidadAsteriscos = 1;
        int cantidadEspacios = numero-1;
        for(int i=1;i<=numero;i++){
            String espacios = generarEspacios(cantidadEspacios);
            String asteriscos = generarAsteriscos(cantidadAsteriscos);
            cantidadEspacios -= 1;
            cantidadAsteriscos +=1;
            lineas += espacios+asteriscos+saltoLinea;
        }
        txtResultadoDerecha.setText(lineas);
    }
    
    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed
       this.dispose();
       eje3 j3 = new eje3();
       j3.setVisible(true);
    }//GEN-LAST:event_btnanteriorActionPerformed

    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        this.hide();
        eje5 frm = new eje5();
        frm.show();
        //frm.setVisible(true);
    }//GEN-LAST:event_btnsiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eje4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eje4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eje4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eje4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eje4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JButton btnvisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtResultadoCentrado;
    private javax.swing.JTextArea txtResultadoDerecha;
    private javax.swing.JTextArea txtResultadoIzquierda;
    private javax.swing.JTextField txtnumero;
    // End of variables declaration//GEN-END:variables
}
