/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formularios;

/**
 *
 * @author BEPIS
 */
public class eje4 extends javax.swing.JFrame {

    /**
     * Creates new form eje4
     */
    public eje4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        btnvisualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtresultado3 = new javax.swing.JTextArea();
        btnanterior = new javax.swing.JButton();
        btnsiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtresultado2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtresultado1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Asterisco");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel2.setText("Ingrese un numero");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        getContentPane().add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 110, -1));

        btnvisualizar.setText("visualizar");
        btnvisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvisualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnvisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 80, -1));

        txtresultado3.setColumns(20);
        txtresultado3.setRows(5);
        jScrollPane2.setViewportView(txtresultado3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 160, 140));

        btnanterior.setText("Anterior");
        btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 80, -1));

        btnsiguiente.setText("Siguiente");
        btnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnsiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 80, -1));

        txtresultado2.setColumns(20);
        txtresultado2.setRows(5);
        jScrollPane1.setViewportView(txtresultado2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 160, 140));

        txtresultado1.setColumns(20);
        txtresultado1.setRows(5);
        jScrollPane3.setViewportView(txtresultado1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvisualizarActionPerformed
        int numero, i,j;
        String caracter="",simbolo="*";
        
        txtresultado1.setText("");
        numero=Integer.parseInt(txtnumero.getText());
        
        for(i=1;i<=numero;i++){
        caracter=caracter + simbolo;
        txtresultado1.append(caracter+"\n");
        }
        
        txtresultado2.setText("");
        numero=Integer.parseInt(txtnumero.getText());
         for(j=1;j<=numero;j--){
        caracter=caracter + simbolo;
        txtresultado2.append(caracter+"\n");
        }
         
         txtresultado3.setText("");
        numero=Integer.parseInt(txtnumero.getText());
          for(i=1;i<=numero;i++){
        caracter=caracter + simbolo;
        txtresultado3.append(caracter+"\n");
        }
         
           
    }//GEN-LAST:event_btnvisualizarActionPerformed

    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed
       this.dispose();
       eje3 j3 = new eje3();
       j3.setVisible(true);
    }//GEN-LAST:event_btnanteriorActionPerformed

    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        this.hide();
        eje5 frm = new eje5();
        frm.show();
        //frm.setVisible(true);
    }//GEN-LAST:event_btnsiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eje4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eje4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eje4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eje4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eje4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JButton btnvisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextArea txtresultado1;
    private javax.swing.JTextArea txtresultado2;
    private javax.swing.JTextArea txtresultado3;
    // End of variables declaration//GEN-END:variables
}
